# -*- coding: utf-8 -*-
"""Entry Challenge V1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S_AP7Izl1_hm1jNPdI7TazX98mLqGcA8
"""

#Function called addition that takes in two numbers and returns the total
def addition(num1, num2):
  sum = num1 + num2;2
  #return value
  return sum;

#Allow user to input values
num1 = int(input("Enter the first number: ", ))
num2 = int(input("Enter the second number: ", ))

#Displays the sum of the two numbers
print("The sum of the the two numbers is: ", addition(num1, num2))